name: 🚀 Release new version

on:
  schedule:
    - cron: "0 3 * * *" # Every day at 3:00 UTC
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      actions: write

    steps:
      - name: 🤖 Use App Token for the Bot which is allowed to create releases
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: 📥 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # Required for fetching tags and generating release notes
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: 🔧 Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global push.followTags true

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Fetch release version
        id: upstream
        run: |
          release_version=$(npm view material-icon-theme version)
          current_version=$(npm list material-icon-theme --depth=0 | grep 'material-icon-theme@' | cut -d '@' -f 2)
          echo "release_version=$release_version" >> $GITHUB_ENV
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: ❌ Cancel if no new release is required
        if: ${{ env.release_version == env.current_version && github.event_name == 'schedule' }}
        run: echo "No new release required. Exiting..." && exit 0

      - name: 🔄 Attempt update
        if: ${{ env.release_version != env.current_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Update the material icon theme dependency to the latest major version (to avoid breaking changes)
        run: |
          npm run update
          npm install material-icon-theme@5.x

      - name: 🏗️ Build extension
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build

      - name: 📜 Generate changelog and release notes
        env:
          # Don't run husky on `git commit`
          HUSKY: 0
        run: |
          npx changelogen --hideAuthorEmail --release --push
          npx changelogen github release --token ${{ secrets.GITHUB_TOKEN }}

      - name: 📝 Get metadata
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 🌐 Upload to chrome store
        continue-on-error: true
        uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7 # v2
        with:
          extension: bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc
          zip: github-material-icons-chrome-extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: 🌐 Upload to edge store
        continue-on-error: true
        uses: wdzeng/edge-addon@e307af4adb6d4e1c12387dc7d6bd545dcd075909 # v1.2.5
        with:
          product-id: f95e9c6a-6470-45a1-ae09-821d3b916923
          zip-path: github-material-icons-edge-extension.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - name: 🌐 Upload to firefox store
        continue-on-error: true
        run: npx web-ext sign -s ./dist/firefox/ --channel=listed --api-key=${{ secrets.FIREFOX_API_JWT_ISSUER }} --api-secret=${{ secrets.FIREFOX_API_JWT_SECRET }}

      - name: ⬆️ Upload zip files to GitHub release
        run: |
          gh release upload v$VERSION github-material-icons-chrome-extension.zip github-material-icons-edge-extension.zip github-material-icons-firefox-extension.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
