name: Auto Update when upstream releases
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: 🤖 Use App Token for the Bot which is allowed to create releases
        uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: 📥 Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🛠️ Setup Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: "20"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔍 Fetch release version
        id: upstream
        run: |
          release_tag=$(npm view material-icon-theme version)
          current_tag=$(npm list material-icon-theme --depth=0 | grep 'material-icon-theme@' | cut -d '@' -f 2)
          echo "release_tag=$release_tag" >> $GITHUB_ENV
          echo "current_tag=$current_tag" >> $GITHUB_ENV

      - name: 🔄 Attempt update
        if: env.release_tag != env.current_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run update
          npm i material-icon-theme@5.x

      - name: 📝 Get package version
        if: env.release_tag != env.current_tag
        run: |
          echo "package_version=v$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: 💾 Commit updated files
        if: env.release_tag != env.current_tag
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "."
          message: "[auto] update to upstream ${{env.release_tag}}"
          tag: "${{env.package_version}}"

      - name: 🚀 Release
        if: env.release_tag != env.current_tag
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{env.package_version}}"
          body: Built with icons from VSCode Material Icon Theme ${{env.release_tag}}
          files: "*.zip"
          generate_release_notes: true

      - name: 🌐 Upload to chrome store
        if: env.release_tag != env.current_tag
        continue-on-error: true
        uses: trmcnvn/chrome-addon@7fc5a5ad3ff597dc64d6a13de7dcaa8515328be7 # v2
        with:
          extension: bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc
          zip: github-material-icons-chrome-extension.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: 🌐 Upload to edge store
        if: env.release_tag != env.current_tag
        continue-on-error: true
        uses: wdzeng/edge-addon@e307af4adb6d4e1c12387dc7d6bd545dcd075909 # v1.2.5
        with:
          product-id: d7692295-d84f-4bf5-9447-3cbb6ae29517
          zip-path: github-material-icons-edge-extension.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}

      - name: 🌐 Upload to firefox store
        if: env.release_tag != env.current_tag
        continue-on-error: true
        run: npx web-ext sign -s ./dist/firefox/ --channel=listed --api-key=${{ secrets.FIREFOX_API_JWT_ISSUER }} --api-secret=${{ secrets.FIREFOX_API_JWT_SECRET }}
